### ISSUE TITLE
Challenge 1 - generate the output from the diagram

### ISSUE THREAD

**Issue by muneebullashariff** [muneeb-mbytes/UVMF#1]
The first team to do following will be announced the winner:

- [x] #3
- [x] #4
- [x] Successfully Generate the output to a custom folder
- [x] Explain why the output generated source files are correct based on the source diagram in a document 
- [x] Submit the changes to their respective branch 
- [x] Create a pull request and add Muneeb as the reviewer.

**Comment by muneebullashariff** [comment]
Input Diagram:

![8C048128-ADE6-4FF9-8F89-D07D363B04AE](https://user-images.githubusercontent.com/15922511/208056485-80f77b3a-e82b-4127-b8a2-733a99b52674.jpeg)

**Comment by nayanarudramurthy** [comment]
Came up with solution, need your approval.

**Comment by muneebullashariff** [comment]
Hi Nayana, 
Good to hear this. The challenge will get completed when team finishes all 6 tasks mentioned.

**Comment by nayanarudramurthy** [comment]
Hi Muneeb,
Our team done with all 6 tasks, so do we need to close issue or just create a pull request

**Comment by muneebullashariff** [comment]
I can see the pull request now, thanks.

Review will be done on Monday.
